export const HOTBAR_SLOT_COUNT = 10;
export const MAX_HOTBAR_INDEX = HOTBAR_SLOT_COUNT - 1;

export const BUILD_PLACEMENT_MAX_DISTANCE = 160;
export const CRAFTING_STATION_INTERACT_PADDING = 48;
export const CRAFTING_STATION_QUERY_RADIUS = 160;

export const MAX_CHAT_MESSAGE_LENGTH = 240;

export const CHEST_INTERACT_PADDING = 48;
export const CHEST_INTERACT_RADIUS = 160;
export const CHEST_SLOT_COUNT = 30;
export const MAX_CHEST_INDEX = CHEST_SLOT_COUNT - 1;

export const RECYCLER_INTERACT_PADDING = 80;
export const TOWER_INTERACT_PADDING = 80;
