import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type ContentCategoryDefinition = {
  directory: string;
  exportName: string;
  parserExpression: (resourceName: string, importName: string) => string;
};

const CONTENT_CATEGORY_DEFINITIONS: readonly ContentCategoryDefinition[] = [
  {
    directory: "building",
    exportName: "buildingContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("building", ${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "structure",
    exportName: "structureContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("structure", ${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "effect",
    exportName: "effectContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEffectContentEntry(${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "enemy",
    exportName: "enemyContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("enemy", ${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "item",
    exportName: "itemContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedItemContentEntry(${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "pickup",
    exportName: "pickupContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("pickup", ${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "player",
    exportName: "playerContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("player", ${JSON.stringify(resourceName)}, ${importName})`,
  },
  {
    directory: "projectile",
    exportName: "projectileContentEntries",
    parserExpression: (resourceName, importName) =>
      `makeParsedEntityContentEntry("projectile", ${JSON.stringify(resourceName)}, ${importName})`,
  },
] as const;

function toIdentifier(value: string): string {
  const words = value
    .replace(/\.json$/i, "")
    .split(/[^a-zA-Z0-9]+/g)
    .filter(Boolean);
  const [firstWord = "content", ...restWords] = words;
  const camelCase = [
    firstWord.toLowerCase(),
    ...restWords.map(
      (word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
    ),
  ].join("");
  return `${camelCase}Json`;
}

async function getSortedResourceNames(
  directoryPath: string,
): Promise<string[]> {
  const directoryEntries = await readdir(directoryPath, {
    withFileTypes: true,
  });
  return directoryEntries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name.replace(/\.json$/i, ""))
    .sort((left, right) => left.localeCompare(right));
}

async function main(): Promise<void> {
  const scriptPath = fileURLToPath(import.meta.url);
  const repoRoot = path.resolve(path.dirname(scriptPath), "..");
  const sharedContentRoot = path.join(repoRoot, "packages/shared/src/content");
  const outputPath = path.join(sharedContentRoot, "generated/manifest.ts");

  const importLines: string[] = [];
  const arrayBlocks: string[] = [];

  for (const category of CONTENT_CATEGORY_DEFINITIONS) {
    const directoryPath = path.join(sharedContentRoot, category.directory);
    const resourceNames = await getSortedResourceNames(directoryPath);
    const entries = resourceNames.map((resourceName) => {
      const importName = `${category.directory}${toIdentifier(resourceName)}`;
      importLines.push(
        `import ${importName} from "@shared/content/${category.directory}/${resourceName}.json";`,
      );
      return `  ${category.parserExpression(resourceName, importName)},`;
    });

    arrayBlocks.push(
      `export const ${category.exportName} = [\n${entries.join("\n")}\n] as const;`,
    );
  }

  const fileContents = [
    "// Generated by scripts/generate-content-manifest.ts. Do not edit by hand.",
    ...importLines,
    "import {",
    "  makeParsedEffectContentEntry,",
    "  makeParsedEntityContentEntry,",
    "  makeParsedItemContentEntry,",
    '} from "@shared/content/parseContent.ts";',
    "",
    ...arrayBlocks.flatMap((block, index) =>
      index === arrayBlocks.length - 1 ? [block, ""] : [block, "", ""],
    ),
  ].join("\n");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, fileContents);
  const prettier = Bun.spawnSync({
    cmd: ["bunx", "prettier", "--write", outputPath],
    cwd: repoRoot,
    stderr: "inherit",
    stdout: "inherit",
  });
  if (prettier.exitCode !== 0) {
    throw new Error(
      `Failed to format generated manifest at ${path.relative(repoRoot, outputPath)}.`,
    );
  }

  process.stdout.write(`Updated ${path.relative(repoRoot, outputPath)}\n`);
}

await main();
