import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { InputIntentMessageSchema } from "@shared/net/protocol.ts";

const GENERATED_HEADER = `// Generated by scripts/generate-fast-input-parser.ts from InputIntentMessageSchema.
// Do not edit by hand.
`;

const OUTPUT_RELATIVE_PATH = "apps/server/src/net/FastInputMessageParser.ts";

function assertInputIntentSchemaShape(): void {
  const shape = InputIntentMessageSchema.shape;
  const requiredKeys = ["t", "seq", "theta", "movement"] as const;
  for (const key of requiredKeys) {
    if (!(key in shape)) {
      throw new Error(
        `InputIntentMessageSchema is missing required field "${key}"`,
      );
    }
  }
  if (!("clientTimeMs" in shape)) {
    throw new Error(
      'InputIntentMessageSchema is missing optional field "clientTimeMs"',
    );
  }
}

const GENERATED_SOURCE = `${GENERATED_HEADER}import { isJsonObject, isJsonValue, parseJsonValue } from "@shared/json.ts";
import { normalizeAngle } from "@shared/math/angle.ts";
import type {
  InputIntentMessage,
  MoveIntentKey,
} from "@shared/net/protocol.ts";

type FastInputMessageParseResult =
  | { kind: "input"; message: InputIntentMessage }
  | { kind: "other" }
  | { kind: "invalid" };

const MOVE_KEYS: ReadonlySet<MoveIntentKey> = new Set([
  "up",
  "down",
  "left",
  "right",
]);
const INPUT_MESSAGE_KEYS = new Set([
  "t",
  "seq",
  "clientTimeMs",
  "theta",
  "movement",
]);

export function parseFastInputMessage(
  rawMessage: string,
): FastInputMessageParseResult {
  // Most inbound traffic is high-frequency movement/aim input.
  if (!rawMessage.includes('"t":"input"')) {
    return { kind: "other" };
  }

  const parsed = parseJsonValue(rawMessage);
  if (!parsed || !isJsonObject(parsed) || parsed.t !== "input") {
    return { kind: "invalid" };
  }
  for (const key of Object.keys(parsed)) {
    if (!INPUT_MESSAGE_KEYS.has(key)) {
      return { kind: "invalid" };
    }
  }
  if ("x" in parsed || "y" in parsed) {
    return { kind: "invalid" };
  }

  const seq = parseNonNegativeInt(parsed.seq);
  const clientTimeMs =
    parsed.clientTimeMs === undefined
      ? undefined
      : parseFiniteNumber(parsed.clientTimeMs);
  const theta = parseFiniteNumber(parsed.theta);
  const movement = parsed.movement;
  if (
    seq === null ||
    clientTimeMs === null ||
    theta === null ||
    !isInputMovement(movement)
  ) {
    return { kind: "invalid" };
  }

  return {
    kind: "input",
    message: {
      t: "input",
      seq,
      ...(clientTimeMs === undefined ? {} : { clientTimeMs }),
      theta: normalizeAngle(theta),
      movement,
    },
  };
}

function parseNonNegativeInt(value: unknown): number | null {
  if (
    typeof value !== "number" ||
    !Number.isFinite(value) ||
    !Number.isInteger(value) ||
    value < 0
  ) {
    return null;
  }
  return value;
}

function parseFiniteNumber(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return null;
  }
  return value;
}

function isInputMovement(
  value: unknown,
): value is InputIntentMessage["movement"] {
  if (!value || !isJsonValue(value) || !isJsonObject(value)) {
    return false;
  }
  for (const key of Object.keys(value)) {
    if (!MOVE_KEYS.has(key as MoveIntentKey)) {
      return false;
    }
  }
  for (const key of MOVE_KEYS) {
    if (typeof value[key] !== "boolean") {
      return false;
    }
  }
  return true;
}
`;

async function main(): Promise<void> {
  assertInputIntentSchemaShape();
  const repoRoot = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "..",
  );
  const outputPath = path.join(repoRoot, OUTPUT_RELATIVE_PATH);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, GENERATED_SOURCE);
  process.stdout.write(`Updated ${OUTPUT_RELATIVE_PATH}\n`);
}

await main();
